check-counting:
	python3 test-bonus.py test counting

check-counting-bonus:
	python3 test-bonus.py test counting --no-global-config

check: check-counting check-counting-bonus

clean:
	rm -rf test-*/*.out_produced
